authors:
  Eg0:
    name: Harlequinz Eg0
    description: Canadian Rocket Scientist and Open-Source Software Developer for OpenNaja
    avatar: https://avatars.githubusercontent.com/u/2275463?v=4
    slug: Harlequinz-Eg0
    url: https://github.com/harlequinzeg0
  Hendrix:
    name: HENDRIX-ZT2
    description: I develop Blender plugins and audio restoration & isolation tools with Python.
    avatar: https://avatars.githubusercontent.com/u/28632661?v=4
    slug: HENDRIX-ZT2
    url: https://github.com/HENDRIX-ZT2
  Inaki:
    name: Inaki
    description: ""
    avatar: https://avatars.githubusercontent.com/u/28944639?v=4
    slug: Inaki
    url: https://github.com/ilodev
  Hexabit:
    name: Hexabit
    description: ""
    avatar: https://avatars.githubusercontent.com/u/170077?v=4
    slug: Hexabit
    url: https://github.com/hexabits
