remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Cobra Tools
description: .
tagline: this is the tagline
logo: /assets/images/open-naja.png
show_downloads: true

author:
  name:  Open-Naja
  email: ignore@gmail.com
  social:
    github:  None
  about: Hi, just a small bio about...